
##################################
# CONFIGURATION VERSION
version: v3.0                                      # 0

##################################
# ALLOWED TOPICS
# Allowing ROS2 HelloWorld demo_nodes topic

allowlist:
  - name: rt/chatter                               # 1
    type: std_msgs::msg::dds_::String_             # 1

##################################
# PARTICIPANTS
participants:

##################################
# SIMPLE PARTICIPANT
# This participant will subscribe to topics in allowlist in domain 0 and listen every message published there

  - name: SimpleROS2                               # 2
    kind: local                                    # 3
    domain: 0                                      # 4

##################################
# ROS DISCOVERY SERVER
# This participant will subscribe to topics in allowlist using Discovery Server protocol as Server


  - name: WANServerROS2                                              # 6
    kind: local-discovery-server                                    # 7
    discovery-server-guid:
      id: 1                                                       # 8
    listening-addresses:                                          # 9
      - ip: 192.168.1.107                                               # 10
        port: 11888                                               # 11
        transport: tcp     
                                                  