version: v3.0 # 0

##################################
# ALLOWED TOPICS
# Allowing ROS2 HelloWorld demo_nodeso

##################################
# PARTICIPANTS
participants:
  - name: DDS_LAN_B
    kind: local

  - name: Router_Client
    kind: wan
    connection-addresses:
      - ip: 192.168.1.107
        port: 11777
        transport: tcp
