controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_base_controller:
      type: diff_drive_controller/DiffDriveController

    ubiquity_motor:
      type: ubiquity_motor/UbiquityMotorSystemHardware

ubiquity_motor:
  ros__parameters:
    hardware:
      type: "ubiquity_motor/UbiquityMotorSystemHardware"
      joints:
        - name: "left_wheel_joint"
          state_interfaces: ["position", "velocity", "effort"]
          command_interfaces: ["position"]
        - name: "right_wheel_joint"
          state_interfaces: ["position", "velocity", "effort"]
          command_interfaces: ["position"]

diff_drive_base_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    interface_name: position
    wheel_separation: 0.3
    wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
    wheel_radius: 0.1

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 100.0
    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal: [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]

    open_loop: false
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    publish_limited_velocity: true
    use_stamped_vel: false
    velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 1.0
    angular.z.min_acceleration: -1.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0


joy_teleop:
  ros__parameters:
    autorepeat_rate: 0.0
    move:
      type: topic
      interface_type: geometry_msgs/msg/Twist
      topic_name: /diff_drive_base_controller/cmd_vel_unstamped
      deadman_buttons: [4]
      axis_mappings:
        linear-x:
          axis: 1
          scale: 0.5
          offset: 0
        angular-z:
          axis: 0
          scale: 0.5
          offset: 0
        
